Models/ErrorViewModel.cs
namespace EstudiantesApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EstudianteController.cs
using EstudiantesApp.Dominio.IServices;
using EstudiantesApp.Transporte;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace EstudiantesApp.Controllers
{
    public class EstudianteController : Controller
    {
        private readonly IEstudianteService _IEstudianteService;
        public EstudianteController(IEstudianteService iEstudianteService)
        {
            _IEstudianteService = iEstudianteService;
        }
        //GET: EstudianteController
        public async Task<ActionResult> Index()
        {
            var estudiantes = await _IEstudianteService.ConsultaEstudiantes();
            return View(estudiantes);
        }
        //GET: EstudianteController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            EstudianteDTO estudiante = await _IEstudianteService.ConsultaEstudiante(id);
            return View(estudiante);
        }
        //GET: EstudianteController/Create
        public ActionResult Create()
        {
            return View();
        }
        //POST: EstudianteController/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<ActionResult> Create(IFormCollection collection)
        {
            try
            {
                EstudianteDTO estudiante = Formulario(collection); 
                var respuesta = await _IEstudianteService.CrearEstudiante(estudiante);

                if(respuesta == false)
                {
                    TempData["Error"] = "Ocurrió un error en la creación";
                }
                else
                {
                    TempData["Exito"] = "Creación exitosa";
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private EstudianteDTO Formulario(IFormCollection collection)
        {
            return new EstudianteDTO
            {
                Id = int.Parse(string.IsNullOrEmpty(collection["Id"]) ? "0" : collection["Id"]),
                Nombres = collection["Nombres"],
                Apellidos = collection["Apellidos"],
                FechaInscripcion = collection["FechaInscripcion"],
            };
        }

        // GET: EstudianteController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            EstudianteDTO estudiante = await _IEstudianteService.ConsultaEstudiante(id);
            return View(estudiante);
        }

        //POST: EstudianteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            try
            {
                EstudianteDTO estudiante = Formulario(collection);
                var fecha = "" + collection["FechaDate"];
                var fechaDate = DateTime.Parse(fecha);
                estudiante.FechaInscripcion = fechaDate.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);
                var respuesta = await _IEstudianteService.EditarEstudiante(estudiante);

                if (respuesta == false)
                {
                    TempData["Error"] = "Ocurrió un error en la edición";
                }
                else
                {
                    TempData["Exito"] = "Edición exitosa";
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //GET: EstudianteController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            EstudianteDTO estudiante = await _IEstudianteService.ConsultaEstudiante(id);
            return View(estudiante);
        }

        //POST: EstudianteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                var respuesta = await _IEstudianteService.EliminarEstudiante(id);

                if (respuesta == false)
                {
                    TempData["Error"] = "Ocurrió un error en la eliminación";
                }
                else
                {
                    TempData["Exito"] = "Eliminación exitosa";
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HomeController.cs
using EstudiantesApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EstudiantesApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Estudiante/Create.cshtml
@model EstudiantesApp.Transporte.EstudianteDTO

@{
    ViewData["Title"] = "Create";
}

<h2 class="text-info">Creación de estudiante</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInscripcion" class="control-label"></label>
                <input asp-for="FechaInscripcion" type="date" class="form-control" />
                <span asp-validation-for="FechaInscripcion" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-6">
                        <input type="submit" value="Create" class="btn btn-primary form-comtrol" />
                    </div>
                    <div class="col-sm-6">
                        <a asp-action="Index" class="btn btn-success form-control">Volver a lista</a>
                    </div>
                </div>               
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudiante/Delete.cshtml
@model EstudiantesApp.Transporte.EstudianteDTO

@{
    ViewData["Title"] = "Delete";
}

<h2 class="text-info">Eliminar estudiante</h2>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInscripcion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <input type="submit" value="Eliminar" class="btn btn-danger form-control" /> |
                </div>
                <div class="col-sm-2">
                    <a asp-action="Index" class="btn btn-success form-control">Volver a lista</a>
                </div>
            </div>
        </div>      
    </form>
</div>

Views/Estudiante/Details.cshtml
@model EstudiantesApp.Transporte.EstudianteDTO

@{
    ViewData["Title"] = "Details";
}

<h2 class="text-info">Detalle del estudiante</h2>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInscripcion)
        </dd>
    </dl>
</div>
<div class="form-group">
    <div class="row">
        <div class="col-sm-2">
            @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary form-control" }) |
        </div>
        <div class="col-sm-2">
            <a asp-action="Index" class="btn btn-success form-control">Volver a lista</a>
        </div>
    </div>
    

</div>

Views/Estudiante/Edit.cshtml
@model EstudiantesApp.Transporte.EstudianteDTO

@{
    ViewData["Title"] = "Edit";
}

<h2 class="text-info">Editar Estudiante</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id"/>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDate" class="control-label"></label>
                <input asp-for="FechaDate" class="form-control" />
                <span asp-validation-for="FechaDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-6">
                        <input type="submit" value="Guardar" class="btn btn-primary form-control" />
                    </div>
                    <div class="col-sm-6">
                        <a asp-action="Index" class="btn btn-success form-control">Volver a lista</a>
                    </div>
                </div>             
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudiante/Index.cshtml
@model IEnumerable<EstudiantesApp.Transporte.EstudianteDTO>

@{
    ViewData["Title"] = "Index";
}

<h2 class="text-info">Lista de estudiantes</h2>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>

@if (TempData["Exito"] != null)
{
    <div class="alert alert-success alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Éxito!</strong> @TempData["Exito"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Error!</strong> @TempData["Error"]
    </div>
}

<p>
    <a asp-action="Create">Crear un nuevo estudiante</a>
</p>
@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombres)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellidos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaInscripcion)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombres)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellidos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaInscripcion)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
                        @Html.ActionLink("Detalle", "Details", new { id=item.Id }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No hay estudiantes inscritos</p>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EstudiantesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EstudiantesApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EstudiantesApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiante" asp-action="Index">Estudiante</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EstudiantesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>